# Generated by Django 2.1.7 on 2019-03-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='pig.png', on_delete=django.db.models.deletion.CASCADE, to='instructors.Instructor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
