# Generated by Django 2.1.7 on 2019-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_module_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='thumb',
            new_name='image_content',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='body',
            new_name='text_content',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='body',
        ),
        migrations.AddField(
            model_name='component',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
