# Generated by Django 2.1.7 on 2019-03-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190320_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='status',
            new_name='open_status',
        ),
    ]
