# Generated by Django 2.2b1 on 2019-03-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190321_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='choice_text',
            field=models.CharField(default='some choice', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.CharField(default='some question', max_length=200),
        ),
    ]
