# Generated by Django 2.2b1 on 2019-03-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190323_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchoice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
