# Generated by Django 2.1.7 on 2019-03-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_module_thumb'),
        ('courses', '0006_auto_20190321_0229'),
    ]

    operations = [
    ]
